DevOps zadatak
tomkaboris/zadatak pull request #2
Opened 2024-11-08 21:06 UTC by tomkaboris

- Prvi zadatak je implementiran u PowerShell-u na osnovu predloženih pretpostavki.
- Drugi zadatak je urađen u Python-u kako bi se kreiralo testno okruženje za prvi zadatak.
Verujem da ovim pristupom, oba zadatka zadovoljavaju tražene zahteve.

2024-11-18 10:51 UTC, majkinetor requested changes
Ne postoji opis parametara i kada ga pokrenem kao po uputstvu dobijem grešku. Folder koji traži je na pogrešnoj lokaciji.

Nastaviću dalje kada se ovo sredi.

2024-11-18 10:51 UTC, majkinetor commented on README.md
> +- **Step 3:** Delete any existing ZIP files with *_sve-partije  if they exists.
Iz originalnog README.md

> Ponavljanje procesa bilo kada ne pravi razliku ako nije bilo promena fajl sistema

Pošto ti brišeš unapred sve partije ako već postoji, ovo nije idempotentno - iako će sadržaj fajla biti isti, menja mu modification time. Modification time se u opštem slučaju koristi za soritiranje.

2024-11-18 10:51 UTC, majkinetor commented on README.md
> +pwsh kdi.ps1
```
-ChildItem: C:\Work\test\zadatak\kdi.ps1:37
Line |
  37 |          $this.OrgIdFolders = Get-ChildItem -Path $basePath -Directory
     |                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\Users\mmilic\izvodi' because it does not exist.
```

2024-11-18 15:23 UTC, majkinetor commented
FYI, mock generiše prazne fajlove, što je generalno marker da nešto nije u redu. Dodati u mock generisanje neki podatak.

2024-11-18 15:25 UTC, majkinetor commented
FYI2, prettify mock JSONS. Svako ko radi analizu podataka ima da se smori uz konstatno gledanje JSONa u jednoj liniji.

2024-11-18 15:28 UTC, majkinetor commented on README.md
> +pwsh kdi.ps1
Suština

1. Ja sam random inženjer koji je dobio da koristi ovo što si uradio
2. Nisam se uopšte ili posebno bavio pwsh
3. Defaulti treba da budu takvi da sve radi, uostalom, piše u README šta treba da radim, i ako to nije tako, instant turn down.

U ovom slučaju izvodi po defaultu treba da budu mokovani u root folder skripte i da skripta tu prvo gleda, a ne u mom HOME diru gde to nikada u životu neće da se nalazi.

Little things se nakupe.

2024-11-20 17:55 UTC, tomkaboris commented on README.md
> +pwsh kdi.ps1
Lose sam razumeo pretpostavku. Sve vreme sam radio kao da je "izvodi" user na systemu.
"_Alat/skript se izvršava na Linux serveru gde se nalaze izvodi i ima read/write prava pristupa **root folderu izvoda**
 - Dizajniran je za upotrebu putem cron job-a_"
 
Hvala na pojasnjenju. Ispravicu.

2024-11-20 18:04 UTC, majkinetor commented on README.md
> +pwsh kdi.ps1
Slobodno otvori tiket ovde za sva pitanja koja imaš

2024-11-21 09:45 UTC, majkinetor commented on README.md
> +pwsh kdi.ps1
> sve vreme sam radio kao da je "izvodi" user na systemu.

User nije bitan. Skripta radi pod nekim userom koji ima read/write prva na folder izvoda.

2024-11-28 16:29 UTC, tomkaboris commented
Zdravo Miodraze,

Uneo sam izmene u skripti:
- [ ] Validacija foldera:
Skripta sada proverava da li folder **izvodi** postoji u root folderu skripte. Ako folder ne postoji, izbacuje poruku i prekida dalju radnju.

- [ ] Provera i rekreiranje ZIP arhive: 
Prilikom ponovnog pokretanja skripte, proverava se sadrzaj arhive mb_sve-partije.zip i novo kreiranog foldera mb_sve-partije.
Ako se sadrzaji ne podudaraju, brise se stara arhiva i kreira nova. Ako nema izmena, novo kreirani folder se brise. Na ovaj nacin zadrzava se originalni modification time arhive ukoliko nije bilo promena u fajl sistemu.

- [ ] Izmene u mock funkcionalnosti:
Dodato generisanje fajlova koji sadrze neke podatke.
Dodato generisanje JSON fajlova sa formatom indent=4 radi bolje preglednosti.

2024-12-02 00:53 UTC, tomkaboris commented
Dodatno sam unapredio skriptu tako da folder izvodi moze biti definisan kao parametar.

Slazem se da ponovnim pokretanjem skripte i proverom sadrzaja u arhivi mb_sve-partije.zip u poredjenju sa novokreiranim folderom mb_sve-partije moze biti sporo. Moja inicijalna ideja bila je fokusirana na jednostavnost u tom trenutku. Svakako postoje bolje opcije, poput koriscenja `last modification time` ili generisanja JSON fajla sa stanjem poslednjeg uspesno kreiranog KDI-a za buduce uporedjivanje (ako je to uopste ok kao opcija). 

Ipak, nazalost, moram da Vas obavestim da necu nastaviti dalje u ovom procesu selekcije. Iako izuzetno uzivam u pisanju skripti i resavanju izazova, trenutne obaveze, kako profesionalne tako i porodicne, ne ostavljaju dovoljno prostora za dodatno vreme koje je potrebno za ovakve testove.

Hvala Vam jos jednom na razumevanju i na ukazanoj prilici.

2024-12-02 10:22 UTC, majkinetor commented
> Ipak, nazalost, moram da Vas obavestim da necu nastaviti dalje u ovom procesu selekcije. Iako izuzetno uzivam u pisanju skripti i resavanju izazova, trenutne obaveze, kako profesionalne tako i porodicne, ne ostavljaju dovoljno prostora za dodatno vreme koje je potrebno za ovakve testove.

U redu. Podrav.

2024-12-02 10:22 UTC, closed without merging